CREATE TABLE `anuncio` (
  `codAnuncio` int NOT NULL AUTO_INCREMENT,
  `codUsuario` int NOT NULL,
  `codTipoAnuncio` varchar(150) COLLATE utf8mb3_unicode_ci NOT NULL,
  `codAtividade` text COLLATE utf8mb3_unicode_ci NOT NULL,
  `codPA` text COLLATE utf8mb3_unicode_ci,
  `codOrigem` int DEFAULT NULL,
  `codDuplicado` int DEFAULT NULL,
  `tags` text COLLATE utf8mb3_unicode_ci,
  `codCaderno` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `codUf` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL,
  `codCidade` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL,
  `descAnuncio` text COLLATE utf8mb3_unicode_ci,
  `descAnuncioFriendly` text COLLATE utf8mb3_unicode_ci,
  `descImagem` text COLLATE utf8mb3_unicode_ci,
  `descEndereco` text COLLATE utf8mb3_unicode_ci,
  `descTelefone` text COLLATE utf8mb3_unicode_ci NOT NULL,
  `descCelular` text COLLATE utf8mb3_unicode_ci,
  `descDescricao` text COLLATE utf8mb3_unicode_ci,
  `descSite` text COLLATE utf8mb3_unicode_ci,
  `descSkype` text COLLATE utf8mb3_unicode_ci,
  `descPromocao` text COLLATE utf8mb3_unicode_ci,
  `descEmailComercial` text COLLATE utf8mb3_unicode_ci,
  `descEmailRetorno` text COLLATE utf8mb3_unicode_ci,
  `descFacebook` text COLLATE utf8mb3_unicode_ci,
  `descTweeter` text COLLATE utf8mb3_unicode_ci,
  `descWhatsApp` text COLLATE utf8mb3_unicode_ci,
  `descCEP` text COLLATE utf8mb3_unicode_ci,
  `descTipoPessoa` text COLLATE utf8mb3_unicode_ci NOT NULL,
  `descCPFCNPJ` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `descNomeAutorizante` text COLLATE utf8mb3_unicode_ci,
  `descEmailAutorizante` text COLLATE utf8mb3_unicode_ci,
  `descParceiro` text COLLATE utf8mb3_unicode_ci,
  `descParceiroLink` text COLLATE utf8mb3_unicode_ci,
  `codDesconto` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL,
  `descLat` text COLLATE utf8mb3_unicode_ci,
  `descLng` text COLLATE utf8mb3_unicode_ci,
  `formaPagamento` text COLLATE utf8mb3_unicode_ci,
  `logoPromocao` text COLLATE utf8mb3_unicode_ci,
  `linkPromo` varchar(255) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `promocaoData` text COLLATE utf8mb3_unicode_ci,
  `descContrato` text COLLATE utf8mb3_unicode_ci,
  `descAndroid` text COLLATE utf8mb3_unicode_ci,
  `descApple` text COLLATE utf8mb3_unicode_ci,
  `descInsta` text COLLATE utf8mb3_unicode_ci,
  `descPatrocinador` text COLLATE utf8mb3_unicode_ci,
  `descPatrocinadorLink` text COLLATE utf8mb3_unicode_ci,
  `qntVisualizacoes` text COLLATE utf8mb3_unicode_ci NOT NULL,
  `activate` int NOT NULL,
  `moderacao` varchar(12) COLLATE utf8mb3_unicode_ci NOT NULL,
  `dtCadastro` datetime DEFAULT NULL,
  `dtCadastro2` datetime DEFAULT NULL,
  `dtAlteracao` datetime DEFAULT NULL,
  `descLinkedin` text COLLATE utf8mb3_unicode_ci,
  `descTelegram` text COLLATE utf8mb3_unicode_ci,
  `certificado_logo` text COLLATE utf8mb3_unicode_ci,
  `certificado_texto` text COLLATE utf8mb3_unicode_ci,
  `certificado_imagem` text COLLATE utf8mb3_unicode_ci,
  `descYouTube` text COLLATE utf8mb3_unicode_ci,
  `link_comprar` text COLLATE utf8mb3_unicode_ci,
  `cashback_logo` text COLLATE utf8mb3_unicode_ci,
  `cashback_link` text COLLATE utf8mb3_unicode_ci,
  `certificado_link` text COLLATE utf8mb3_unicode_ci,
  `cartao_digital` text COLLATE utf8mb3_unicode_ci,
  `descChavePix` text COLLATE utf8mb3_unicode_ci,
  `descDonoPix` varchar(255) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `periodo` text COLLATE utf8mb3_unicode_ci,
  `page` varchar(255) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `dueDate` datetime DEFAULT NULL,
  `createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`codAnuncio`),
  KEY `idx_tags` (`tags`(255)),
  KEY `idx_codDesconto` (`codDesconto`),
  KEY `idx_activate` (`activate`),
  KEY `idx_createdAt_codDuplicado` (`createdAt` DESC),
  KEY `idx_anuncio_order` (`activate`,`createdAt` DESC),
  KEY `idx_anuncio_busca` (`codUf`,`codCaderno`,`page`,`codAtividade`(20)),
  KEY `idx_anuncio_consulta` (`codUf`,`codCaderno`,`codAtividade`(20)),
  KEY `idx_anuncio_filtro` (`codUf`,`codCaderno`),
  KEY `idx_cnpj` (`descCPFCNPJ`(20)),
  KEY `idx_anuncio_descAnuncio` (`descAnuncio`(100)),
  KEY `idx_codAtividade` (`codAtividade`(100)),
  KEY `idx_codDuplicado` (`codDuplicado`),
  KEY `idx_anuncio_activate_created_codduplicado` (`activate`,`createdAt` DESC,`codDuplicado`),
  KEY `idx_descEmailRetorno` (`descEmailRetorno`(255)),
  KEY `idx_descTelefone` (`descTelefone`(80)),
  KEY `idx_descCelular` (`descCelular`(80))
) ENGINE=InnoDB AUTO_INCREMENT=19920092 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;